import assert from 'node:assert/strict';
import fs from 'node:fs';
import { describe, it, type TestContext } from 'node:test';

import * as VizPackage from '@viz-js/viz';

import * as DotVizPackage from '../src/index.ts';

const useVizJS = process.env.USE_VIZ_JS != null;
const dotviz = useVizJS
  ? await VizPackage.instance()
  : await DotVizPackage.instance();

// FIXME: many files are modified with replaced fonts and removed unicode symbols
// update after we fully support native fonts
describe('GraphViz Gallery', () => {
  /* spell-checker: disable */
  describe('directed', () => {
    it('gallery/directed/bazel.gv', snapshotGvFile);
    it('gallery/directed/cluster.gv', snapshotGvFile);
    it('gallery/directed/crazy.gv', snapshotGvFile);
    it('gallery/directed/datastruct.gv', snapshotGvFile);
    it('gallery/directed/fsm.gv', snapshotGvFile);
    it('gallery/directed/Genetic_Programming.gv', snapshotGvFile);
    it('gallery/directed/git.gv', snapshotGvFile);
    it('gallery/directed/go-package.gv', snapshotGvFile);
    it('gallery/directed/hello.gv', snapshotGvFile);
    it.skip('kennedyanc.gv', snapshotGvFile);
    it('gallery/directed/Linux_kernel_diagram.gv', snapshotGvFile);
    it('gallery/directed/lion_share.gv', snapshotGvFile);
    it('gallery/directed/neural-network.gv', snapshotGvFile);
    it('gallery/directed/ninja.gv', snapshotGvFile);
    it('gallery/directed/pprof.gv', snapshotGvFile);
    it('gallery/directed/profile.gv', snapshotGvFile);
    it('gallery/directed/psg.gv', snapshotGvFile);
    it('gallery/directed/sdh.gv', snapshotGvFile);

    // FIXME: viz-js also crashes on bellow graph
    // digraph {graph[label="\nKappa Kappa Psi/Tau Beta Sigma\nSan Diego State University"]}
    it.skip('gallery/directed/siblings.gv', snapshotGvFile);

    it('gallery/directed/switch.gv', snapshotGvFile);
    it('gallery/directed/UML_Class_diagram.gv', snapshotGvFile);
    it('gallery/directed/unix.gv', snapshotGvFile);
    it('gallery/directed/world.gv', snapshotGvFile);
  });
  describe.skip('fdp', () => {
    it('gallery/fdp/fdpclust.gv', snapshotGvFile);
  });
  describe('gradient', () => {
    it('gallery/gradient/angles.gv', snapshotGvFile);
    it('gallery/gradient/cluster.gv', snapshotGvFile);
    it('gallery/gradient/colors.gv', snapshotGvFile);
    it('gallery/gradient/datastruct.gv', snapshotGvFile);
    it('gallery/gradient/g_c_n.gv', snapshotGvFile);
    it('gallery/gradient/linear_angle.gv', snapshotGvFile);
    it('gallery/gradient/radial_angle.gv', snapshotGvFile);
    it('gallery/gradient/table.gv', snapshotGvFile);
  });
  describe.skip('neato', () => {
    it('gallery/neato/color_wheel.gv', snapshotGvFile);
    it('gallery/neato/colors.gv', snapshotGvFile);
    it('gallery/neato/ER.gv', snapshotGvFile);
    it('gallery/neato/philo.gv', snapshotGvFile);
    it('gallery/neato/process.gv', snapshotGvFile);
    it('gallery/neato/softmaint.gv', snapshotGvFile);
    it('gallery/neato/traffic_lights.gv', snapshotGvFile);
    it('gallery/neato/transparency.gv', snapshotGvFile);
  });
  describe.skip('sfdp', () => {
    it('gallery/sfdp/root.gv', snapshotGvFile);
  });
  describe.skip('twopi', () => {
    it('gallery/twopi/happiness.gv', snapshotGvFile);
    it('gallery/twopi/networkmap_twopi.gv', snapshotGvFile);
    it('gallery/twopi/twopi2.gv', snapshotGvFile);
  });
  describe('undirected', () => {
    it('gallery/undirected/gd_1994_2007.gv', snapshotGvFile);
    it('gallery/undirected/grid.gv', snapshotGvFile);
    it('gallery/undirected/inet.gv', snapshotGvFile);
  });
  /* spell-checker: enable */
});

function snapshotGvFile(ctx: TestContext) {
  const gvPath = ctx.name;
  const result = dotviz.renderFormats(
    fs.readFileSync('./test/' + gvPath, 'utf8'),
    ['dot', 'svg'],
  );

  const output = result.output;
  assert.deepStrictEqual(result, { status: 'success', output, errors: [] });

  const dot = output?.dot;
  const svg = useVizJS
    ? output?.svg.replaceAll(
        'Generated by graphviz version 13.1.2 (20250808.2320)',
        'Generated by graphviz version a (a)',
      )
    : output?.svg;

  const basePath = gvPath.replace(/\.gv$/, '');
  const serializers = [(str: string) => str];
  ctx.assert.fileSnapshot(dot, `./test/${basePath}.dot`, { serializers });
  ctx.assert.fileSnapshot(svg, `./test/${basePath}.svg`, { serializers });
}
