import assert from 'node:assert/strict';
import fs from 'node:fs';
import { describe, it, type TestContext } from 'node:test';

import * as VizPackage from '@viz-js/viz';

import * as DotVizPackage from '../src/index.ts';

const useVizJS = process.env.USE_VIZ_JS != null;
const dotviz = useVizJS
  ? await VizPackage.instance()
  : await DotVizPackage.instance();

// FIXME: many files are modified with replaced fonts and removed unicode symbols
// update after we fully support native fonts
describe('GraphViz Gallery', () => {
  /* spell-checker: disable */
  describe('directed', () => {
    it('bazel', testCase('directed/bazel'));
    it('cluster', testCase('directed/cluster'));
    it('crazy', testCase('directed/crazy'));
    it('datastruct', testCase('directed/datastruct'));
    it('fsm', testCase('directed/fsm'));
    // FIXME it('Genetic_Programming', testCase('directed/Genetic_Programming'));
    // FIXME it('git', testCase('directed/git'));
    it('go-package', testCase('directed/go-package'));
    it('hello', testCase('directed/hello'));
    it.skip('kennedyanc', testCase('directed/kennedyanc'));
    it('Linux_kernel_diagram', testCase('directed/Linux_kernel_diagram'));
    it('lion_share', testCase('directed/lion_share'));
    it('neural-network', testCase('directed/neural-network'));
    it('ninja', testCase('directed/ninja'));
    it('pprof', testCase('directed/pprof'));
    it('profile', testCase('directed/profile'));
    it('psg', testCase('directed/psg'));
    it('sdh', testCase('directed/sdh'));
    // FIXME it('siblings', testCase('directed/siblings'));
    it('switch', testCase('directed/switch'));
    it('UML_Class_diagram', testCase('directed/UML_Class_diagram'));
    it('unix', testCase('directed/unix'));
    it('world', testCase('directed/world'));
  });
  describe.skip('fdp', () => {
    it('fdpclust', testCase('fdp/fdpclust'));
  });
  describe('gradient', () => {
    it('angles', testCase('gradient/angles'));
    it('cluster', testCase('gradient/cluster'));
    it('colors', testCase('gradient/colors'));
    it('datastruct', testCase('gradient/datastruct'));
    it('g_c_n', testCase('gradient/g_c_n'));
    it('linear_angle', testCase('gradient/linear_angle'));
    it('radial_angle', testCase('gradient/radial_angle'));
    it('table', testCase('gradient/table'));
  });
  describe.skip('neato', () => {
    it('color_wheel', testCase('neato/color_wheel'));
    it('colors', testCase('neato/colors'));
    it('ER', testCase('neato/ER'));
    it('philo', testCase('neato/philo'));
    it('process', testCase('neato/process'));
    it('softmaint', testCase('neato/softmaint'));
    it('traffic_lights', testCase('neato/traffic_lights'));
    it('transparency', testCase('neato/transparency'));
  });
  describe.skip('sfdp', () => {
    it('root', testCase('sfdp/root'));
  });
  describe.skip('twopi', () => {
    it('happiness', testCase('twopi/happiness'));
    it('networkmap_twopi', testCase('twopi/networkmap_twopi'));
    it('twopi2', testCase('twopi/twopi2'));
  });
  describe('undirected', () => {
    it('gd_1994_2007', testCase('undirected/gd_1994_2007'));
    it('grid', testCase('undirected/grid'));
    it('inet', testCase('undirected/inet'));
  });
  /* spell-checker: enable */
});

function testCase(path: string) {
  return (ctx: TestContext) => {
    const result = dotviz.renderFormats(
      fs.readFileSync(`./test/gallery/${path}.gv`, 'utf8'),
      ['dot', 'svg'],
    );

    const dot = result.output?.dot;
    let svg = result.output?.svg;
    assert.deepStrictEqual(result, {
      status: 'success',
      output: { dot, svg },
      errors: [],
    });

    ctx.assert.fileSnapshot(dot, `./test/gallery/${path}.dot`, {
      serializers: [(str: string) => str],
    });

    if (useVizJS && svg != null) {
      svg = svg.replaceAll(
        'Generated by graphviz version 14.0.1 (20251006.0113)',
        'Generated by graphviz version a (a)',
      );
    }
    ctx.assert.fileSnapshot(svg, `./test/gallery/${path}.svg`, {
      serializers: [(str: string) => str],
    });
  };
}
