import { describe, expect, it } from 'vitest';

import * as VizPackage from '../src/index.ts';
import { expectString } from './util/raw-string-serializer.ts';
import { expectFailureResult } from './util/render-result.ts';

describe('Viz', () => {
  describe('renderFormats', () => {
    it('renders multiple output formats', async () => {
      const viz = await VizPackage.instance();
      const result = viz.renderFormats('graph a { }', ['dot', 'svg']);

      expect(result).toStrictEqual({
        status: 'success',
        output: {
          dot: expect.any(String) as unknown,
          svg: expect.any(String) as unknown,
        },
        errors: [],
      });
      expectString(result.output?.dot).toMatchInlineSnapshot(`
        graph a {
        	graph [bb="0,0,0,0"];
        	node [label="\\N"];
        }
      `);
      expectString(result.output?.svg).toMatchInlineSnapshot(`
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
         "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
        <!-- Generated by graphviz version a (a)
         -->
        <!-- Title: a Pages: 1 -->
        <svg width="8pt" height="8pt"
         viewBox="0.00 0.00 8.00 8.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 4)">
        <title>a</title>
        <polygon fill="white" stroke="none" points="-4,4 -4,-4 4,-4 4,4 -4,4"/>
        </g>
        </svg>
      `);
    });

    it('renders with the same format twice', async () => {
      const viz = await VizPackage.instance();
      const result = viz.renderFormats('graph a { }', ['dot', 'dot']);

      expect(result).toStrictEqual({
        status: 'success',
        output: {
          dot: expect.any(String) as unknown,
        },
        errors: [],
      });
      expectString(result.output?.dot).toMatchInlineSnapshot(`
        graph a {
        	graph [bb="0,0,0,0"];
        	node [label="\\N"];
        }
      `);
    });

    it('renders with an empty array of formats', async () => {
      const viz = await VizPackage.instance();
      const result = viz.renderFormats('graph a { }', []);

      expect(result).toStrictEqual({
        status: 'success',
        output: {},
        errors: [],
      });
    });

    it('returns error messages for invalid input', async () => {
      const viz = await VizPackage.instance();
      const result = viz.renderFormats('invalid', ['dot', 'svg']);

      expectFailureResult(result).toMatchInlineSnapshot(`
        [
          {
            "level": "error",
            "message": "Unexpected identifier 'invalid', expected keyword 'strict', 'graph' or 'digraph' at the beginning of the file.",
          },
        ]
      `);
    });

    it('returns error messages for invalid input and an empty array of formats', async () => {
      const viz = await VizPackage.instance();
      const result = viz.renderFormats('invalid', []);

      expectFailureResult(result).toMatchInlineSnapshot(`
        [
          {
            "level": "error",
            "message": "Unexpected identifier 'invalid', expected keyword 'strict', 'graph' or 'digraph' at the beginning of the file.",
          },
        ]
      `);
    });
  });
});
