import assert from 'node:assert/strict';
import { beforeEach, describe, it } from 'node:test';

import * as VizPackage from '../src/index.js';

describe('Viz', function () {
  let viz;

  beforeEach(async function () {
    viz = await VizPackage.instance();
  });

  describe('renderFormats', function () {
    it('renders multiple output formats', function () {
      const result = viz.renderFormats('graph a { }', ['dot', 'svg']);

      assert.deepStrictEqual(result, {
        status: 'success',
        output: {
          dot: 'graph a {\n\tgraph [bb="0,0,0,0"];\n\tnode [label="\\N"];\n}\n',
          svg:
            '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n' +
            '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n' +
            ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n' +
            '<!-- Generated by graphviz version a (a)\n' +
            ' -->\n' +
            '<!-- Title: a Pages: 1 -->\n' +
            '<svg width="8pt" height="8pt"\n' +
            ' viewBox="0.00 0.00 8.00 8.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n' +
            '<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 4)">\n' +
            '<title>a</title>\n' +
            '<polygon fill="white" stroke="none" points="-4,4 -4,-4 4,-4 4,4 -4,4"/>\n' +
            '</g>\n' +
            '</svg>\n',
        },
        errors: [],
      });
    });

    it('renders with the same format twice', function () {
      const result = viz.renderFormats('graph a { }', ['dot', 'dot']);

      assert.deepStrictEqual(result, {
        status: 'success',
        output: {
          dot: 'graph a {\n\tgraph [bb="0,0,0,0"];\n\tnode [label="\\N"];\n}\n',
        },
        errors: [],
      });
    });

    it('renders with an empty array of formats', function () {
      const result = viz.renderFormats('graph a { }', []);

      assert.deepStrictEqual(result, {
        status: 'success',
        output: {},
        errors: [],
      });
    });

    it('returns error messages for invalid input', function () {
      const result = viz.renderFormats('invalid', ['dot', 'svg']);

      assert.deepStrictEqual(result, {
        status: 'failure',
        output: undefined,
        errors: [
          { level: 'error', message: "syntax error in line 1 near 'invalid'" },
        ],
      });
    });

    it('returns error messages for invalid input and an empty array of formats', function () {
      const result = viz.renderFormats('invalid', []);

      assert.deepStrictEqual(result, {
        status: 'failure',
        output: undefined,
        errors: [
          { level: 'error', message: "syntax error in line 1 near 'invalid'" },
        ],
      });
    });
  });
});
