#include "../output_string.h"
#include "cgraph.h"
#include "const.h"
#include "geom.h"
#include "geomprocs.h"
#include "gvc.h" // IWYU pragma: keep
#include "gvcext.h"
#include "gvcint.h" // IWYU pragma: keep
#include "gvcjob.h"
#include "gvplugin_render.h" // IWYU pragma: keep
#include "render_svg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core_svg.h"
#include "safe_job.h"
#include "types.h"

output_string inner_render_svg(GVC_t *gvc, GVJ_t *job, Agraph_t *g) {
  /* page size on Linux, Mac OS X and Windows */
  output_string output = {.data_position = 0, .data_allocated = 4096};
  if (!(output.data = malloc(output.data_allocated))) {
    agerrorf("failure malloc'ing for result string");
    exit(-1);
  }

  const char *stylesheet = agget(g, "stylesheet");
  svg_begin_job(&output, stylesheet);
  // FIXME: remove hardcode
  svg_comment(&output, "Generated by graphviz version a (a)\n");

  pointf pad = {.x = 4., .y = 4.};
  if (gvc->graph_sets_pad) {
    pad = gvc->pad;
  }

  // SafeJob:
  int layerNum = job->layerNum;
  point pagesArrayElem = job->pagesArrayElem;

  char **defaultlinestyle = gvc->defaultlinestyle;
  char **layerIDs = gvc->layerIDs;
  char *layerDelims = gvc->layerDelims;
  char *layerListDelims = gvc->layerListDelims;
  int numLayers = gvc->numLayers;

  /* margin - in points - in page orientation */
  pointf margin = (pointf){0, 0}; // margin for a page of the graph - points
  if (gvc->graph_sets_margin) {
    margin = gvc->margin;
  }

  pointf dpi = (pointf){72, 72}; // FIXME: make dpi single value
  if (GD_drawing(g)->dpi != 0) {
    dpi.x = dpi.y = GD_drawing(g)->dpi;
  }

  int rv;
  Agnode_t *n;
  char *str, *nodename = NULL;

  pointf UR = gvc->bb.UR;
  pointf LL = gvc->bb.LL;
  boxf bb = {
      .LL = sub_pointf(LL, pad),
      .UR = add_pointf(UR, pad)}; // bb is bb of graph and padding - graph units

  pointf sz = sub_pointf(bb.UR,
                         bb.LL); // size, including padding - graph units

  /* view gives port size in graph units, unscaled or rotated
   * zoom gives scaling factor.
   * focus gives the position in the graph of the center of the port
   */
  double zoom = 1.0; /* scaling factor */

  /* determine final drawing size and scale to apply. */
  /* N.B. size given by user is not rotated by landscape mode */
  /* start with "natural" size of layout */

  if (GD_drawing(g)->size.x > 0.001 &&
      GD_drawing(g)->size.y > 0.001) { /* graph size was given by user... */
    pointf size = GD_drawing(g)->size;
    if (sz.x <= 0.001)
      sz.x = size.x;
    if (sz.y <= 0.001)
      sz.y = size.y;
    if (size.x < sz.x ||
        size.y < sz.y             /* drawing is too big (in either axis) ... */
        || (GD_drawing(g)->filled /* or ratio=filled requested and ... */
            && size.x > sz.x &&
            size.y > sz.y)) /* drawing is too small (in both axes) ... */
      zoom = fmin(size.x / sz.x, size.y / sz.y);
  }

  /* default focus, in graph units = center of bb */
  pointf focus = scale(0.5, add_pointf(LL, UR));

  /* rotate and scale bb to give default absolute size in points*/
  int rotation = gvc->rotation;
  pointf view = scale(zoom, sz);

  /* user can override */
  if ((str = agget(g, "viewport"))) {
    nodename = gv_alloc(strlen(str) + 1);
    rv = sscanf(str, "%lf,%lf,%lf,\'%[^\']\'", &view.x, &view.y, &zoom,
                nodename);
    if (rv == 4) {
      n = agfindnode(g->root, nodename);
      if (n) {
        focus = ND_coord(n);
      }
    } else {
      rv = sscanf(str, "%lf,%lf,%lf,%[^,]%c", &view.x, &view.y, &zoom, nodename,
                  &(char){0});
      if (rv == 4) {
        n = agfindnode(g->root, nodename);
        if (n) {
          focus = ND_coord(n);
        }
      } else {
        sscanf(str, "%lf,%lf,%lf,%lf,%lf", &view.x, &view.y, &zoom, &focus.x,
               &focus.y);
      }
    }
    free(nodename);
  }

  /* unpaginated image size - in points - in graph orientation */
  pointf imageSize = view; // image size on one page of the graph - points

  /* rotate imageSize to page orientation */
  if (rotation)
    imageSize = exch_xyf(imageSize);

  /* initial window size */
  unsigned int width =
      ROUND((imageSize.x + 2 * margin.x) * dpi.x / POINTS_PER_INCH);
  unsigned int height =
      ROUND((imageSize.y + 2 * margin.y) * dpi.y / POINTS_PER_INCH);

  // FIXME: add warning about ignoring centering attribute
  // https://graphviz.org/docs/attrs/center/

  /* rotate back into graph orientation */
  if (rotation) {
    margin = exch_xyf(margin);
  }

  /* canvas area, centered if necessary */
  boxf canvasBox = {0};
  canvasBox.LL.x = margin.x;
  canvasBox.LL.y = margin.y;
  canvasBox.UR.x = margin.x + view.x;
  canvasBox.UR.y = margin.y + view.y;

  /* pageBoundingBox in device units and page orientation */
  box pageBoundingBox = {0};
  pageBoundingBox.LL.x = ROUND(canvasBox.LL.x * dpi.x / POINTS_PER_INCH);
  pageBoundingBox.LL.y = ROUND(canvasBox.LL.y * dpi.y / POINTS_PER_INCH);
  pageBoundingBox.UR.x = ROUND(canvasBox.UR.x * dpi.x / POINTS_PER_INCH);
  pageBoundingBox.UR.y = ROUND(canvasBox.UR.y * dpi.y / POINTS_PER_INCH);
  if (rotation) {
    pageBoundingBox.LL = exch_xy(pageBoundingBox.LL);
    pageBoundingBox.UR = exch_xy(pageBoundingBox.UR);
    canvasBox.LL = exch_xyf(canvasBox.LL);
    canvasBox.UR = exch_xyf(canvasBox.UR);
  }

  /* size of one page in graph units */
  double pageSize_x = view.x / zoom;
  double pageSize_y = view.y / zoom;
  boxf clip = {0};
  clip.LL.x = focus.x - pageSize_x / 2.0;
  clip.LL.y = focus.y - pageSize_y / 2.0;
  clip.UR.x = clip.LL.x + pageSize_x;
  clip.UR.y = clip.LL.y + pageSize_y;

  SafeJob safe_job = {
      .layerNum = layerNum,
      .pagesArrayElem = pagesArrayElem,
      .dpi = dpi,
      .rotation = rotation,
      .pageBoundingBox = pageBoundingBox,
      .height = height,
      .width = width,
      .canvasBox = canvasBox,
      .zoom = zoom,
      .clip = clip,

      // from gvc
      .graph = g,
      .defaultlinestyle = defaultlinestyle,
      .layerIDs = layerIDs,
      .layerDelims = layerDelims,
      .layerListDelims = layerListDelims,
      .numLayers = numLayers,
  };
  emit_graph(&output, &safe_job, job->obj, g, gvc->layerlist, job->flags);

  return output;
}
